environments:
  dev:
  prod:

---

repositories:
 - name: sputnik
   url: https://gitlab.sirius.online/api/v4/projects/176/packages/helm/stable
   username: zerodistance
   password: glpat-dxTFQxAzC1PJV-3Ec62y

releases:
- name: ory-hydra
  namespace: auth-dev
  chart: sputnik/ory-hydra
  values:
    - envs/{{ .Environment.Name }}/values/univ.yaml
#    - image:
#        tag: "1.0.0"